<?php
/**
 * This class was automatically generated by GraphQL Schema generator
 */

namespace AppBundle\GraphQL;

use AppBundle\GraphQL\Category\CategoriesField;
use AppBundle\GraphQL\Part\PartField;
use AppBundle\GraphQL\Part\PartsField;
use AppBundle\GraphQL\Part\RelatedPartsField;
use Youshido\GraphQL\Schema\AbstractSchema;
use Youshido\GraphQL\Config\Schema\SchemaConfig;

class Schema extends AbstractSchema
{
    public function build(SchemaConfig $config)
    {
        $config->getQuery()->addFields([
            new PartsField(),
            new PartField(),
            new CategoriesField(),
            new RelatedPartsField()
        ]);
    }

}

