graphql:
    resource: "@GraphQLBundle/Controller/"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /{reactRouting}
    defaults: { _controller: AppBundle:Default:index, reactRouting: null }
    requirements:
        reactRouting: ".+"